---
- name: Ensure flathub repo remote exists in system installation.
  community.general.flatpak_remote:
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    name: flathub
    state: present
  become: true
  become_user: root
